spring:
  profiles:
    active: dev

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml

server:
  servlet:
    context-path: /grdtg
  port: 8090

submission:
  taskFlow:
    id: submissionTaskFlow #文稿工作流流程对应码表ID
    systemDealId: sub #文稿工作流系统处理人ID
    sustemDealName: sub
  weixin:
    applyUserId: 896322  #微信提交文稿时，默认用户ID